<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="NAVMCTMTTL108" name="Voice line Service" tests="2" failures="2" timestamp="9 Jul 2020 23:18:39 GMT" time="187.64" errors="0">
  <testcase name="verifyServicepanelinviewservicepage" time="186.233" classname="com.saksoft.qa.apttestscripts.APT_VoiceLineTest">
    <failure type="java.lang.AssertionError" message=" on clicking &amp;apos;Show Infovista link&amp;apos;, it got naviagted to SSO Login Page expected [SSO login Page] but found [SSO Login Page]">
      <![CDATA[java.lang.AssertionError:  on clicking 'Show Infovista link', it got naviagted to SSO Login Page expected [SSO login Page] but found [SSO Login Page]
	at com.saksoft.qa.scripthelpers.APT_VoiceLineHelper.shownewInfovista(APT_VoiceLineHelper.java:6346)
	at com.saksoft.qa.scripthelpers.APT_VoiceLineHelper.verifyservicepanel_links(APT_VoiceLineHelper.java:1076)
	at com.saksoft.qa.apttestscripts.APT_VoiceLineTest.verifyServicepanelinviewservicepage(APT_VoiceLineTest.java:92)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- verifyServicepanelinviewservicepage -->
  <testcase name="verifyServicepanelinviewservicepage" time="186.764" classname="com.saksoft.qa.apttestscripts.APT_VoiceLineTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.saksoft.qa.listeners.TestListener.onTestFailure(TestListener.java:66)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 7 stack frames]]>
    </failure>
  </testcase> <!-- verifyServicepanelinviewservicepage -->
</testsuite> <!-- Voice line Service -->
